name: Depoy to GitHub

on:
  # push:
  #   branches:
  #     - main  # Set a branch name to trigger deployment
  # pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment:
      name: demo
      url: ${{ steps.deploy_to_pages.outputs.github_pages_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Vite Github Pages Deployer
        uses: skywarth/vite-github-pages-deployer@master
        id: deploy_to_pages

    # permissions:
    #   contents: write
    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.ref }}
    # steps:
    #   - uses: actions/checkout@v4
    #     with:
    #       fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    #   - name: Setup Environment
    #     uses: peaceiris/actions-hugo@v2
    #     with:
    #       hugo-version: '0.110.0'

    #   - name: Build
    #     run: hugo --minify

    #   - name: Deploy
    #     uses: peaceiris/actions-gh-pages@v4
    #     # If you're changing the branch from main,
    #     # also change the `main` in `refs/heads/main`
    #     # below accordingly.
    #     if: github.ref == 'refs/heads/main'
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       publish_dir: ./dist